# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otp_google_authenticator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otp_totp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GADevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.TOTPDevice')),
                ('base32_key', models.CharField(default=otp_google_authenticator.models.get_default_key, help_text='A base32 encoded string of up to 10 characters', max_length=16, validators=[otp_google_authenticator.models.base32_validator])),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Google Authenticator Device',
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
